Add 'text' command to parse a single sentence from command line

diff --git a/isf b/isf
--- a/isf
+++ b/isf
@@ -3,9 +3,9 @@
 DEFAULT_HOME=~/local/isf
 
 if [ -z "${ISF_HOME}" ]; then
-    echo "WARNING: ISF_HOME could not be located ..."
+    (>&2 echo "WARNING: ISF_HOME could not be located ...")
     if [ -d ${DEFAULT_HOME} ]; then
-        echo "Defaulting to ${DEFAULT_HOME}"
+        (>&2 echo "Defaulting to ${DEFAULT_HOME}")
         export ISF_HOME=${DEFAULT_HOME}
     fi
 fi
@@ -13,4 +13,4 @@ fi
 if [ ! -z "${ISF_HOME}" ]; then
     export PYTHONPATH=${ISF_HOME}
 fi
-python3 -m coolisf.main $@
+python3 -m coolisf.main "$@"
